import type { Metadata } from "next";
import "../globals.css";
import Navbar from '@/components/Navbar';

export const metadata: Metadata = {
  title: "Kenny Worden - Senior Software Engineer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="apple-touch-icon" sizes="180x180" href="/favicons/apple-touch-icon.png"/>
        <link rel="icon" type="image/png" sizes="32x32" href="/favicons/favicon-32x32.png"/>
        <link rel="icon" type="image/png" sizes="16x16" href="/favicons/favicon-16x16.png"/>
        <link rel="manifest" href="/favicons/site.webmanifest"/>
      </head>
      <body>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
